[package]
name = "electrical"
version = "0.1.0"
authors = ["Joseph Frazer <frazer380@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
